export const coffeeArray = [
  {
    id: "coffee-10",
    name: "Black Cat",
    image: "images/coffee-10.png",
    price: 150,
    description: "Dark roasted beans create a bold and intense flavor with a smooth finish.",
    type: "drinks",
  },
  {
    id: "coffee-1",
    name: "Café de Olla",
    image: "images/coffee-1.png",
    price: 200,
    description: "A traditional Mexican coffee brewed with cinnamon and piloncillo, offering a sweet and aromatic experience.",
    type: "drinks",
  },
  {
    id: "coffee-9",
    name: "Bourbon Coffee",
    image: "images/coffee-9.png",
    price: 250,
    description: "Made from Bourbon variety beans, this coffee features sweet and fruity notes for a rich flavor.",
    type: "drinks",
  },
  {
    id: "coffee-6",
    name: "Butterfly Latte",
    image: "images/coffee-6.png",
    price: 180,
    description: "A latte infused with butterfly pea flowers and steamed milk, changing color with lemon for a magical touch.",
    type: "drinks",
  },
  {
    id: "coffee-7",
    name: "Kopi Luwak",
    image: "images/coffee-7.png",
    price: 300,
    description: "An exclusive coffee made from beans digested by civets, known for its smooth and unique flavor.",
    type: "drinks",
  },
  {
    id: "coffee-4",
    name: "Yirgacheffe Coffee",
    image: "images/coffee-4.png",
    price: 220,
    description: "Bright and floral Ethiopian coffee with a light acidity, perfect for a nuanced flavor experience.",
    type: "drinks",
  },
  {
    id: "coffee-13",
    name: "Cascara Tea",
    image: "images/coffee-13.png",
    price: 130,
    description: "Tea made from dried coffee cherries, delivering fruity flavors with a refreshing tartness.",
    type: "drinks",
  },
  {
    id: "coffee-14",
    name: "Café Bombón",
    image: "images/coffee-14.png",
    price: 170,
    description: "A Spanish classic with espresso and sweetened condensed milk, creating a rich and creamy coffee.",
    type: "drinks",
  },
  {
    id: "coffee-3",
    name: "Blue Mountain",
    image: "images/coffee-3.png",
    price: 280,
    description: "Renowned Jamaican coffee known for its mild flavor and smooth, well-balanced profile.",
    type: "drinks",
  },
  {
    id: "coffee-8",
    name: "Parisian Coffee",
    image: "images/coffee-8.png",
    price: 160,
    description: "A French favorite combining brewed coffee with steamed milk for a rich and comforting drink.",
    type: "drinks",
  },
  {
    id: "coffee-2",
    name: "Egg Coffee",
    image: "images/coffee-2.png",
    price: 190,
    description: "Vietnamese espresso topped with a frothy mix of egg yolks and condensed milk, offering a sweet and savory taste.",
    type: "drinks",
  },
  {
    id: "coffee-5",
    name: "Peaberry Coffee",
    image: "images/coffee-5.png",
    price: 240,
    description: "Coffee made from peaberry beans, known for a sweeter and more vibrant flavor profile.",
    type: "drinks",
  },
  {
    id: "coffee-11",
    name: "Decaf Nitro",
    image: "images/coffee-11.png",
    price: 130,
    description: "Cold brew coffee infused with nitrogen for a creamy texture and rich flavor without caffeine.",
    type: "drinks",
  },
  {
    id: "coffee-12",
    name: "Moroccan Coffee",
    image: "images/coffee-12.png",
    price: 160,
    description: "Aromatic coffee blend with spices, offering a taste of Moroccan market flavors.",
    type: "drinks",
  }
];


export const bestSellingCoffeeArray = [
  {
    id: "coffee-9",
    name: "Bourbon Coffee",
    image: "images/coffee-9.png",
    price: 250,
    description: "Made from Bourbon variety beans, known for its sweet and fruity flavors.",
    array: 'coffeeArray',
    type: "drinks",
  },
  {
    id: "coffee-6",
    name: "Butterfly Latte",
    image: "images/coffee-6.png",
    price: 180,
    description: "A vibrant drink made with butterfly pea flowers and steamed milk, transforming color with lemon.",
    array: 'coffeeArray',
    type: "drinks",
  },
  {
    id: "noncoffee-2",
    name: "Chai Latte",
    image: "images/noncoffee-2.png",
    price: 230,
    description: "A spiced blend of black tea and aromatic spices mixed with steamed milk, delivering warmth and comfort in every sip.",
    array: 'milkteaArray',
    type: "drinks",
  },
  {
    id: "coffee-7",
    name: "Kopi Luwak",
    image: "images/coffee-7.png",
    price: 300,
    description: "One of the world's most expensive coffees, made from beans digested by civets.",
    array: 'coffeeArray',
    type: "drinks",
  },
  {
    id: "noncoffee-6",
    name: "Oreo Brown Sugar",
    image: "images/noncoffee-6.png",
    price: 160,
    description: "A rich and creamy milk tea infused with the sweetness of brown sugar and the crunch of Oreo cookies, creating a delightful treat that's both indulgent and refreshing.",
    array: 'milkteaArray',
    type: "drinks",
  },
  {
    id: "noncoffee-8",
    name: "Fruit Tea",
    image: "images/noncoffee-8.png",
    price: 150,
    description: "A refreshing blend of herbal tea and assorted fruits, served chilled for a light and fruity experience.",
    array: 'milkteaArray',
    type: "drinks",
  }
];

export const milkteaArray = [
  {
    id: "noncoffee-1",
    name: "Classic Milk",
    image: "images/noncoffee-1.png",
    price: 120,
    description: "A traditional blend of black tea and creamy milk, perfectly sweetened for a comforting drink.",
    type: "drinks",
  },
  {
    id: "noncoffee-7",
    name: "Pink Lemonade",
    image: "images/noncoffee-7.png",
    price: 160,
    description: "A refreshing blend of lemonade with a hint of strawberry, giving it a beautiful pink hue. This drink is both tangy and sweet, perfect for a hot day.",
    type: "drinks",
  },
  {
    id: "noncoffee-11",
    name: "Matcha Latte",
    image: "images/noncoffee-11.png",
    price: 220,
    description: "A smooth fusion of high-quality matcha green tea and creamy milk, offering a vibrant color and unique flavor.",
    type: "drinks",
  },
  {
    id: "noncoffee-8",
    name: "Fruit Tea",
    image: "images/noncoffee-8.png",
    price: 150,
    description: "A refreshing blend of herbal tea and assorted fruits, served chilled for a light and fruity experience.",
    type: "drinks",
  },
  {
    id: "noncoffee-12",
    name: "Taro Milk",
    image: "images/noncoffee-12.png",
    price: 200,
    description: "Creamy milk tea made with taro powder, providing a sweet and nutty flavor with a lovely purple hue.",
    type: "drinks",
  },
  {
    id: "noncoffee-9",
    name: "Chocolate Milk",
    image: "images/noncoffee-9.png",
    price: 180,
    description: "A delightful combination of rich chocolate and creamy milk tea, perfect for satisfying your sweet cravings.",
    type: "drinks",
  },
  {
    id: "noncoffee-4",
    name: "Honey Lemon",
    image: "images/noncoffee-4.png",
    price: 130,
    description: "A soothing blend of honey, fresh lemon, and milk tea, creating a refreshing drink with a hint of sweetness.",
    type: "drinks",
  },
  {
    id: "noncoffee-3",
    name: "Peach Oolong",
    image: "images/noncoffee-3.png",
    price: 190,
    description: "A fragrant oolong tea infused with peach flavor, topped with creamy milk for a fruity and smooth experience.",
    type: "drinks",
  },
  {
    id: "noncoffee-2",
    name: "Chai Latte",
    image: "images/noncoffee-2.png",
    price: 230,
    description: "A spiced blend of black tea and aromatic spices mixed with steamed milk, delivering warmth and comfort in every sip.",
    type: "drinks",
  },
  {
    id: "noncoffee-6",
    name: "Oreo Brown Sugar",
    image: "images/noncoffee-6.png",
    price: 160,
    description: "A rich and creamy milk tea infused with the sweetness of brown sugar and the crunch of Oreo cookies, creating a delightful treat that's both indulgent and refreshing.",
    type: "drinks",
  },
  {
    id: "noncoffee-10",
    name: "Strawberry Shake",
    image: "images/noncoffee-10.png",
    price: 240,
    description: "A delightful blend of fresh strawberries and creamy milk, creating a sweet and refreshing drink perfect for any occasion.",
    type: "drinks",
  },
];

export const burgerArray = [
  {
      id: 'burger-1',
      name: 'Classic Cheeseburger',
      price: 110,
      image: 'images/burger-1.png',
      description: 'A juicy beef patty with melted cheddar, crisp lettuce, ripe tomatoes, and zesty pickles on a toasted sesame bun. The timeless favorite!'
  },
  {
      id: 'burger-2',
      name: 'Bacon Delight',
      price: 120,
      image: 'images/burger-2.png',
      description: 'Indulge in crispy bacon, melted cheddar, fresh lettuce, and tangy mayo atop a thick beef patty. Bacon lovers, rejoice!'
  },
  {
      id: 'burger-3',
      name: 'Spicy Jalapeno',
      price: 130,
      image: 'images/burger-3.png',
      description: 'Turn up the heat with spicy jalapenos, pepper jack cheese, and chipotle mayo on a juicy beef patty. Feel the sizzle!'
  },
  {
      id: 'burger-4',
      name: 'Mushroom Swiss',
      price: 140,
      image: 'images/burger-4.png',
      description: 'Savor sautéed mushrooms, Swiss cheese, and caramelized onions on a savory beef patty. An earthy delight!'
  },
  {
      id: 'burger-5',
      name: 'Double Decker',
      price: 150,
      image: 'images/burger-5.png',
      description: 'Experience smoky BBQ sauce, crispy bacon, and cheddar cheese atop a juicy beef patty. A true BBQ feast!'
  },
  {
      id: 'burger-6',
      name: 'Avocado Ranch Burger',
      price: 115,
      image: 'images/burger-6.png',
      description: 'Enjoy creamy avocado, cool ranch, crisp lettuce, and ripe tomatoes on a beef patty. A fresh twist on a classic!'
  },
  {
      id: 'burger-7',
      name: 'Blue Cheese Bliss',
      price: 125,
      image: 'images/burger-7.png',
      description: 'Delight in tangy blue cheese crumbles, caramelized onions, and a juicy beef patty. Gourmet burger bliss!'
  },
  {
      id: 'burger-8',
      name: 'BBQ Bacon Burger',
      price: 135,
      image: 'images/burger-8.png',
      description: 'Double the beef, double the cheese, with fresh lettuce, tomatoes, and special sauce. Twice the taste, twice the fun!'
  },
  {
      id: 'burger-9',
      name: 'Hawaiian Burger',
      price: 145,
      image: 'images/burger-9.png',
      description: 'Transport yourself to the tropics with grilled pineapple, savory ham, and a tangy teriyaki glaze. Aloha, flavor!'
  },
  {
      id: 'burger-10',
      name: 'Vegan Veggie Burger',
      price: 150,
      image: 'images/burger-10.png',
      description: 'A hearty veggie patty with crisp lettuce, ripe tomatoes, and creamy vegan aioli. Plant-based perfection!'
  }
];

export const pastaArray = [
  {
    id: 'pasta-2',
    name: 'Spicy Arrabbiata',
    image: 'images/pasta-2.png',
    price: 180,
    description: 'A fiery kick of red chili peppers in a rich tomato sauce. Perfectly balanced with garlic and herbs for an unforgettable taste experience.',
    type: 'food',
  },
  {
    id: 'pasta-3',
    name: 'Pesto Chicken',
    image: 'images/pasta-3.png',
    price: 220,
    description: 'Grilled chicken and fresh basil pesto combined for a satisfying meal. The tender chicken is smothered in a fragrant, herbaceous pesto sauce for a hearty dish.',
    type: 'food',
  },
  {
    id: 'pasta-4',
    name: 'Herb Pesto',
    image: 'images/pasta-4.png',
    price: 200,
    description: 'Fresh basil pesto mixed with a blend of herbs and olive oil. This pasta is a fragrant, herbaceous delight with a robust, fresh flavor.',
    type: 'food',
  },
  {
    id: 'pasta-5',
    name: 'Savory Bolognese',
    image: 'images/pasta-5.png',
    price: 240,
    description: 'Rich and hearty Bolognese sauce with minced meat and vegetables. Slow-cooked to perfection, offering a deeply satisfying, meaty taste.',
    type: 'food',
  },
  {
    id: 'pasta-6',
    name: 'Lemon Ricotta',
    image: 'images/pasta-6.png',
    price: 190,
    description: 'Tangy lemon and creamy ricotta cheese for a refreshing taste. The zesty citrus enhances the smooth richness of the cheese, creating a delightful contrast.',
    type: 'food',
  },
  {
    id: 'pasta-7',
    name: 'Garlic Shrimp',
    image: 'images/pasta-7.png',
    price: 260,
    description: 'Juicy shrimp sautéed with garlic and white wine sauce. Infused with aromatic herbs, this dish offers a succulent seafood experience with a touch of elegance.',
    type: 'food',
  },
  {
    id: 'pasta-8',
    name: 'Tuscan Mushroom',
    image: 'images/pasta-8.png',
    price: 230,
    description: 'Earthy mushrooms in a creamy Tuscan sauce with a hint of wine. This rich, velvety sauce combines deep mushroom flavors with a touch of sophisticated flair.',
    type: 'food',
  },
  {
    id: 'pasta-9',
    name: 'Sun-Dried Tomato',
    image: 'images/pasta-9.png',
    price: 210,
    description: 'Sweet and tangy sun-dried tomatoes mixed with a zesty sauce. The concentrated tomato flavor pairs beautifully with a hint of spice for a vibrant taste.',
    type: 'food',
  },
  {
    id: 'pasta-10',
    name: 'Creamy Carbonara',
    image: 'images/pasta-10.png',
    price: 200,
    description: 'Classic Italian carbonara with pancetta and a creamy egg sauce. Each bite is a decadent blend of savory flavors and silky textures.',
    type: 'food',
  },
  {
    id: 'pasta-11',
    name: 'Mediterranean Veggie',
    image: 'images/pasta-11.png',
    price: 250,
    description: 'A medley of Mediterranean vegetables in a light olive oil dressing. Packed with fresh flavors and a touch of garlic, this dish is a colorful, healthy delight.',
    type: 'food',
  },
  {
    id: 'pasta-12',
    name: 'Four Cheese',
    image: 'images/pasta-12.png',
    price: 280,
    description: 'A rich blend of four cheeses melted into a creamy, indulgent sauce. Each forkful is a luxurious experience of gooey, savory goodness that melts in your mouth.',
    type: 'food',
  },
  {
    id: 'pasta-13',
    name: 'Spaghetti Marinara',
    image: 'images/pasta-13.png',
    price: 170,
    description: 'Classic marinara sauce with a touch of garlic and fresh basil. This timeless favorite combines simple ingredients for a comforting, homey meal.',
    type: 'food',
  },
  {
    id: 'pasta-14',
    name: 'Pepperoni Bake',
    image: 'images/pasta-14.png',
    price: 270,
    description: 'Baked pasta with spicy pepperoni and a gooey cheese topping. The crispy, melted cheese and zesty pepperoni create a deliciously satisfying, hearty meal.',
    type: 'food',
  },
  {
    id: 'pasta-15',
    name: 'Cajun Shrimp',
    image: 'images/pasta-15.png',
    price: 260,
    description: 'Cajun-spiced shrimp with a zesty cream sauce for a kick of flavor. This dish combines bold Cajun spices with a smooth, creamy sauce for an exciting taste sensation.',
    type: 'food',
  },
  {
    id: 'pasta-16',
    name: 'Truffle Alfredo',
    image: 'images/pasta-16.png',
    price: 300,
    description: 'Luxurious Alfredo sauce infused with earthy truffle oil. This indulgent pasta offers a rich, sophisticated flavor profile with a velvety texture.',
    type: 'food',
  },
  {
    id: 'pasta-17',
    name: 'Tomato Basil',
    image: 'images/pasta-17.png',
    price: 190,
    description: 'Simple yet divine tomato and basil sauce with a touch of sweetness. This classic combination delivers a comforting, fresh flavor that is both classic and satisfying.',
    type: 'food',
  }
];


export const othersArray = [
  {
    id: 'others-1',
    name: 'Taco Fiesta',
    price: 80,
    image: 'images/others-1.png',
    description: 'Enjoy a flavorful taco fiesta filled with seasoned meat, fresh veggies, a hint of lime, and a delicious blend of spices that will leave you craving for more.',
    type: 'food',
  },
  {
    id: 'others-2',
    name: 'Cherry Ice Cream',
    price: 100,
    image: 'images/others-2.png',
    description: 'Indulge in our creamy ice cream topped with a juicy cherry, offering a perfect combination of sweetness and tanginess that is sure to delight your taste buds.',
    type: 'food',
  },
  {
    id: 'others-3',
    name: 'Sushi Platter',
    price: 200,
    image: 'images/others-3.png',
    description: 'Delight in our fresh and authentic sushi platter, crafted with the finest ingredients and utmost care, providing an exquisite and flavorful dining experience.',
    type: 'food',
  },
  {
    id: 'others-4',
    name: 'Strawberry Dream',
    price: 90,
    image: 'images/others-4.png',
    description: 'Experience the creamy goodness of our strawberry dream ice cream, melting in your mouth with every bite and offering a delightful treat for any time of the day.',
    type: 'food',
  },
  {
    id: 'others-5',
    name: 'Vanilla Bliss',
    price: 90,
    image: 'images/others-5.png',
    description: 'Satisfy your sweet tooth with our rich vanilla bliss ice cream, a perfect blend of creamy vanilla that promises a blissful and indulgent experience.',
    type: 'food',
  },
  {
    id: 'others-6',
    name: 'Veggie Soup',
    price: 70,
    image: 'images/others-6.png',
    description: 'Warm up with our delicious veggie soup, packed with fresh vegetables and savory broth, offering a wholesome and comforting meal that is perfect for any occasion.',
    type: 'food',
  },
  {
    id: 'others-7',
    name: 'Garden Salad',
    price: 60,
    image: 'images/others-7.png',
    description: 'A refreshing garden salad featuring a mix of crisp vegetables and a tangy dressing, providing a light and healthy option that is both satisfying and delicious.',
    type: 'food',
  },
  {
    id: 'others-8',
    name: 'Spicy Taco',
    price: 80,
    image: 'images/others-8.png',
    description: 'A spicy twist on our classic taco, featuring seasoned beef and fresh toppings, delivering a burst of flavors with every bite that will leave you wanting more.',
    type: 'food',
  },
  {
    id: 'others-9',
    name: 'BBQ Skewer',
    price: 120,
    image: 'images/others-9.png',
    description: 'Savor the flavors of our perfectly grilled BBQ skewer, accompanied by a tangy sauce, offering a delightful and mouth-watering experience that is hard to resist.',
    type: 'food',
  },
  {
    id: 'others-10',
    name: 'Fruit Tart',
    price: 110,
    image: 'images/others-10.png',
    description: 'Enjoy a delicious fruit tart filled with a creamy custard and topped with an assortment of fresh fruit, providing a sweet and delightful treat that is both beautiful and tasty.',
    type: 'food',
  },
];


export const pastryArray = [
  {
    id: 'pastry-1',
    name: 'Chocolate Croissant',
    image: 'images/pastry-1.png',
    price: 70,
    description: 'Flaky croissant filled with rich chocolate, perfect for a decadent treat.',
    type: 'food',
  },
  {
    id: 'pastry-2',
    name: 'Blueberry Muffin',
    image: 'images/pastry-2.png',
    price: 60,
    description: 'Sweet muffin bursting with juicy blueberries and a crumbly top.',
    type: 'food',
  },
  {
    id: 'pastry-3',
    name: 'Almond Danish',
    image: 'images/pastry-3.png',
    price: 75,
    description: 'Buttery Danish pastry with a sweet almond filling and a sprinkle of powdered sugar.',
    type: 'food',
  },
  {
    id: 'pastry-4',
    name: 'Cinnamon Roll',
    image: 'images/pastry-4.png',
    price: 65,
    description: 'Soft roll with a gooey cinnamon center, topped with a sweet glaze.',
    type: 'food',
  },
  {
    id: 'pastry-5',
    name: 'Lemon Scone',
    image: 'images/pastry-5.png',
    price: 70,
    description: 'Tangy lemon scone with a hint of sweetness, perfect with a cup of tea.',
    type: 'food',
  },
  {
    id: 'pastry-6',
    name: 'Apple Turnover',
    image: 'images/pastry-6.png',
    price: 80,
    description: 'Flaky pastry filled with spiced apples, ideal for a comforting snack.',
    type: 'food',
  },
  {
    id: 'pastry-7',
    name: 'Raspberry Tart',
    image: 'images/pastry-7.png',
    price: 90,
    description: 'Delicate tart filled with fresh raspberries and a hint of cream.',
    type: 'food',
  },
  {
    id: 'pastry-8',
    name: 'Pecan Pie Bar',
    image: 'images/pastry-8.png',
    price: 85,
    description: 'Sweet and nutty pecan pie bar with a buttery crust.',
    type: 'food',
  },
  {
    id: 'pastry-9',
    name: 'Pumpkin Muffin',
    image: 'images/pastry-9.png',
    price: 70,
    description: 'Moist muffin made with pumpkin and spices, perfect for fall.',
    type: 'food',
  },
  {
    id: 'pastry-10',
    name: 'Caramel Eclair',
    image: 'images/pastry-10.png',
    price: 95,
    description: 'Light eclair filled with creamy caramel and topped with a rich glaze.',
    type: 'food',
  },
];




